# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  # 1. Configuração para o Servidor (Backend)
  - package-ecosystem: "npm"
    directory: "/ignite/server"
    schedule:
      interval: "weekly" # Checa segurança todo dia
    open-pull-requests-limit: 5
    groups:
      server-dependencies:
        patterns: ["*"]

  # 2. Configuração para o App (Mobile)
  - package-ecosystem: "npm"
    directory: "/ignite/mobile"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    # Como o Mobile usa Expo/React 19, ignoramos updates de versão 'major' 
    # automaticamente para evitar que o robô quebre o app sozinho.
    ignore:
      - dependency-name: "react"
        update-types: ["version-update:semver-major"]
      - dependency-name: "react-native"
        update-types: ["version-update:semver-major"]

  # 3. Configuração para o Web (Frontend)
  - package-ecosystem: "npm"
    directory: "/ignite/web"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5